# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      -   id: trailing-whitespace
      -   id: pretty-format-json
          args:
            - "--autofix"
            - "--indent=4"
            - "--no-sort-keys"

  -   repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v21.1.0
      hooks:
      -    id: clang-format
           args: ['-style=file']
           files: '\.(c|cpp|h|hpp|tpp)$'
