#ifndef CGBTESTS_H
#define CGBTESTS_H

#include "testutils/catch.h"
#include "testutils/runners.h"

#include "utils/strings.h"

#define WIP_ONLY_TEST_ROMS 0

#define RUN_TEST_ROMS(...)                                                                                             \
    static RunnerAdapter adapter {TESTS_ROOT_FOLDER "/roms/cgb/", TESTS_ROOT_FOLDER "/results/cgb/"};                  \
    const auto [params] = TABLE(RunnerAdapter::Params, ({__VA_ARGS__}));                                               \
    REQUIRE(adapter.run(params))

TEST_CASE("cgb", "[emulation]") {
#if !WIP_ONLY_TEST_ROMS
    SECTION("boot") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/boot/boot_bg_palettes.gbc", "docboy/ok.png"}, F {"docboy/boot/boot_oam.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_regs_interrupts.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_regs_joypad.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_regs_serial.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_regs_timers.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_regs_video.gbc", "docboy/ok.png"}, F {"docboy/boot/boot_vram1.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_write_oam.gbc", "docboy/ok.png"},
            F {"docboy/boot/boot_write_vram.gbc", "docboy/ok.png"}, );
    }

    SECTION("banks") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/banks/vram_bank_switch.gbc", "docboy/ok.png"},
            F {"docboy/banks/wram_bank_switch.gbc", "docboy/ok.png"});
    }

    SECTION("memory") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/memory/not_usable_area_write.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_area_write_fea0_16_bytes.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_area_write_feb0_16_bytes.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_area_write_fec0_16_bytes.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_area_write_fed0_16_bytes.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_area_write_fee0_16_bytes.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_read_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_read_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_read_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_read_ppu_off.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_read_vblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_write_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_write_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_write_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/not_usable_write_vblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_read_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_read_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_read_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_read_ppu_off.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_read_vblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_write_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_write_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_write_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/oam_write_vblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_read_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_read_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_read_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_read_ppu_off.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_read_vblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_write_hblank.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_write_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_write_pixel_transfer.gbc", "docboy/ok.png"},
            F {"docboy/memory/vram_write_vblank.gbc", "docboy/ok.png"}, );
    }

    SECTION("stat_write_bug") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/stat_write_bug/stat_write_bug_hblank.gbc", "docboy/ok.png"}, );
    }

    SECTION("dma") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/dma/dma_source_ext_routine_cpu_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_cpu_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_cpu_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_cpu_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_vram_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_vram_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_vram_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_vram_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_wram_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_wram_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_wram_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_ext_routine_wram_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_cpu_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_cpu_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_cpu_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_cpu_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_ext_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_ext_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_ext_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_ext_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_wram_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_wram_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_wram_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_vram_routine_wram_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_cpu_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_cpu_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_cpu_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_cpu_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_ext_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_ext_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_ext_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_ext_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_vram_read_cpu.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_vram_read_ext.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_vram_read_vram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_vram_read_wram.gbc", "docboy/ok.png"},
            F {"docboy/dma/dma_source_wram_routine_wram.gbc", "docboy/ok.png"}, );
    }

    SECTION("hdma") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/hdma/gdma_basic_transfer.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_dest_bits.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx4_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_hblank_timing_scx4_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ly_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ly_timing_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_overflow_destination_8000_rollback.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_overflow_destination_8800_rollback.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_overflow_source_illegal.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_overflow_source_rollback.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_hblank.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_32_bytes_sprite_y16_x16.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_48_bytes_sprite_y16_x16.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x01.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x02.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x03.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x04.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x05.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x06.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x07.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x08.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x09.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x11.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x12.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x13.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x14.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x15.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x16.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x17.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x18.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x19.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x20.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x21.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x22.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x23.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x32.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x33.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x34.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x35.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x36.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x37.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x38.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x39.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x40.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x41.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x42.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x43.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x44.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x45.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x46.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x47.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x48.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x49.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_sprite_y16_x50.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx16.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx17.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx18.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx19.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx20.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx21.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx22.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_64_bytes_window_wy1_wx23.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x17.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x18.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x19.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x20.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x21.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x22.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x23.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x10_x24.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x16.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x25.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x26.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x27.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x28.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x29.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x30.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x31.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x32.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x33.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x24_x34.gbc",
               "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x32.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_80_bytes_sprite_y16_x48.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_ppu_on_pixel_transfer_conflict_relaxed_128_bytes_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_bits.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_echo_ram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_from_vram_to_ram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_from_wram2_to_echo_ram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_hram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_io.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_not_usable.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_oam.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_call_in_hram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_corruption.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_jp_in_hram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_jp_in_ram.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_jp_in_wram1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_source_vram_jp_in_wram2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_tima_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_tima_timing_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_transfer_length.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_transfer_max_length.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_transfer_read_ff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_two_transfers.gbc", "docboy/ok.png"},
            F {"docboy/hdma/gdma_two_transfers_write_hdma2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma1_write_read.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma2_write_read.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma3_write_read.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma4_write_read.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_abort_after_0_chunks_remaining_length.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_abort_after_0_chunks_transferred_bytes.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_abort_after_1_chunks_remaining_length.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_abort_after_1_chunks_restart.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_abort_after_1_chunks_transferred_bytes.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_basic_transfer.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_46_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_46_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_46_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_46_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_47_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_47_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_47_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_47_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_at_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_at_oam_scan_remaining_length.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_halt_resume_with_stat_vblank_at_oam_scan_wait_hblanks.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx4_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_hblank_timing_scx4_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_off.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_off_turn_on_after_228_cycles.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_off_turn_on_after_456_cycles.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_off_turn_on_after_912_cycles.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly0_hblank.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly0_hblank_turn_on.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly1_hblank.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly1_hblank_turn_on.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly1_oam_scan.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_ppu_on_turn_off_during_ly1_oam_scan_turn_on.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx0_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx1_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx2_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ly0_scx3_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx0_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx1_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx2_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ld_instr_len_4_scx3_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx0_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx1_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx2_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_4_scx3_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx0_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx1_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx2_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round8.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round9.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_remaining_length_ldh_instr_len_8_scx3_round10.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_after_1_chunks_transferred_bytes_round0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_after_1_chunks_transferred_bytes_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_after_1_chunks_transferred_bytes_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_change_destination.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_change_source.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_change_source_and_destination.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma3_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma3_diff_revert.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma3_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma3_same_hdma4_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma3_same_hdma4_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma4_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_destination_hdma4_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma1_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma1_diff_revert.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma1_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma1_same_hdma2_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma1_same_hdma2_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma2_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_restart_write_source_hdma2_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_source_vram_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_start_during_ly0_hblank_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_start_during_ly0_hblank_timing_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_start_during_ly1_hblank_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_start_during_ly1_hblank_timing_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_stop_resume_47_nops_scx0.gbc", "docboy/ok.png",
               Inputs {{BOOT_DURATION + 20000, Joypad::KeyState::Pressed, Joypad::Key::Up}}},
            F {"docboy/hdma/hdma_stop_resume_wait_hblanks.gbc", "docboy/ok.png",
               Inputs {{BOOT_DURATION + 20000, Joypad::KeyState::Pressed, Joypad::Key::Up}}},
            F {"docboy/hdma/hdma_switch_destination_vram_bank.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_switch_source_wram_bank.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_4_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_4_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx4_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx4_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx5_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx5_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx6_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx6_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx7_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_instr_length_12_scx7_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_ly0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_ly0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx0_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx0_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx1_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx1_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx2_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx2_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx3_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx3_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx4_round1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_scx4_round2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase0_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase1_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase2_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_cb_phase3_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_9_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_10_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_11_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase0_12_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_9_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_10_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_11_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase1_12_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_9_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_10_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_11_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase2_12_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_9_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_10_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_11_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx0.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx1.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx2.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx3.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx4.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx6.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_tima_timing_trigger_phase3_12_nops_scx7.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma5.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma12.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma34.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma123.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma124.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma134.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_transfer_write_hdma234.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_two_transfers.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_destination_hdma3_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_destination_hdma3_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_destination_hdma4_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_destination_hdma4_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_source_hdma1_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_source_hdma1_same.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_source_hdma2_diff.gbc", "docboy/ok.png"},
            F {"docboy/hdma/hdma_write_source_hdma2_same.gbc", "docboy/ok.png"}, );
    }

    SECTION("ir") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/ir/rp_write_read.gbc", "docboy/ok.png"}, );
    }

    SECTION("undocumented") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/undocumented/ff72_write_read.gbc", "docboy/ok.png"},
            F {"docboy/undocumented/ff73_write_read.gbc", "docboy/ok.png"},
            F {"docboy/undocumented/ff74_write_read.gbc", "docboy/ok.png"},
            F {"docboy/undocumented/ff75_write_read.gbc", "docboy/ok.png"});
    }

    SECTION("ppu") {
        RUN_TEST_ROMS(
            // mattcurrie
            F {"mattcurrie/cgb-acid2.gbc", "mattcurrie/cgb-acid2.png"},

            // magen
            F {"magen/bg_oam_priority.gbc", "magen/bg_oam_priority.png"},
            F {"magen/oam_internal_priority.gbc", "magen/oam_internal_priority.png"},

            // samesuite
            F {"samesuite/ppu/blocking_bgpi_increase.gb", "samesuite/ppu/blocking_bgpi_increase.png"},

            // docboy
            F {"docboy/ppu/rendering/bg_attr_bank.gbc", "docboy/ppu/bg_attr_bank.png"},
            F {"docboy/ppu/rendering/bg_attr_horizontal_flip.gbc", "docboy/ppu/bg_attr_horizontal_flip.png"},
            F {"docboy/ppu/rendering/bg_attr_palette.gbc", "docboy/ppu/bg_attr_palette.png"},
            F {"docboy/ppu/rendering/bg_attr_priority.gbc", "docboy/ppu/bg_attr_priority.png"},
            F {"docboy/ppu/rendering/bg_attr_priority_color_0.gbc", "docboy/ppu/bg_attr_priority_color_0.png"},
            F {"docboy/ppu/rendering/bg_attr_priority_color_0_lcdc_bit_0.gbc",
               "docboy/ppu/bg_attr_priority_color_0_lcdc_bit_0.png"},
            F {"docboy/ppu/rendering/bg_attr_priority_lcdc_bit_0.gbc", "docboy/ppu/bg_attr_priority_lcdc_bit_0.png"},
            F {"docboy/ppu/rendering/bg_attr_vertical_flip_scy.gbc", "docboy/ppu/bg_attr_vertical_flip_scy.png"},
            F {"docboy/ppu/rendering/bg_attrs_lcdc_bit_3.gbc", "docboy/ppu/bg_attrs_lcdc_bit_3.png"},
            F {"docboy/ppu/rendering/lcdc_bit_0.gbc", "docboy/ppu/lcdc_bit_0.png"},
            F {"docboy/ppu/rendering/obj_attr_bank.gbc", "docboy/ppu/obj_attr_bank.png"},
            F {"docboy/ppu/rendering/obj_attr_palette.gbc", "docboy/ppu/obj_attr_palette.png"},
            F {"docboy/ppu/rendering/win_attr_bank.gbc", "docboy/ppu/win_attr_bank.png"},
            F {"docboy/ppu/rendering/win_attr_palette.gbc", "docboy/ppu/win_attr_palette.png"},
            F {"docboy/ppu/rendering/win_attrs_lcdc_bit_6.gbc", "docboy/ppu/win_attrs_lcdc_bit_6.png"},
            F {"docboy/ppu/bcpd_write_read.gbc", "docboy/ok.png"}, F {"docboy/ppu/bcps_increment.gbc", "docboy/ok.png"},
            F {"docboy/ppu/bcps_increment_overflow.gbc", "docboy/ok.png"},
            F {"docboy/ppu/ly_timing_round0.gbc", "docboy/ok.png"},
            F {"docboy/ppu/ly_timing_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/ocpd_write_read.gbc", "docboy/ok.png"}, F {"docboy/ppu/ocps_increment.gbc", "docboy/ok.png"},
            F {"docboy/ppu/ocps_increment_overflow.gbc", "docboy/ok.png"},
            F {"docboy/ppu/opri_write_read.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_1_sprite_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_1_sprite_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_2_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_2_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_3_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_3_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_4_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_4_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_5_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_5_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_6_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_6_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_7_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_7_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_8_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_8_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_9_sprites_x32_round1.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_9_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_10_sprites_x32_round2.gbc", "docboy/ok.png"},
            F {"docboy/ppu/pixel_transfer_timing_10_sprites_x32_round2.gbc", "docboy/ok.png"}, );
    }

    SECTION("apu") {
        RUN_TEST_ROMS(
            // docboy
            F {"docboy/apu/ch1/square_position_retrigger_round1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch1/square_position_retrigger_round2.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch1/square_position_round1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch1/square_position_round2.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch1/volume_sweep_round_1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch1/volume_sweep_round_2.gbc", "docboy/ok.png"},

            F {"docboy/apu/ch2/square_position_retrigger_round1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch2/square_position_retrigger_round2.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch2/square_position_round1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch2/square_position_round2.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch2/volume_sweep_round_1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch2/volume_sweep_round_2.gbc", "docboy/ok.png"},

            F {"docboy/apu/ch4/volume_sweep_round_1.gbc", "docboy/ok.png"},
            F {"docboy/apu/ch4/volume_sweep_round_2.gbc", "docboy/ok.png"},

            // samesuite
            F {"samesuite/apu/div_trigger_volume_10.gb", "samesuite/apu/div_trigger_volume_10.png",
               COLOR_TOLERANCE_MEDIUM},
            F {"samesuite/apu/div_write_trigger.gb", "samesuite/apu/div_write_trigger.png", COLOR_TOLERANCE_MEDIUM},
            F {"samesuite/apu/div_write_trigger_10.gb", "samesuite/apu/div_write_trigger_10.png",
               COLOR_TOLERANCE_MEDIUM},
            F {"samesuite/apu/div_trigger_volume_10.gb", "samesuite/apu/div_trigger_volume_10.png",
               COLOR_TOLERANCE_MEDIUM},
            F {"samesuite/apu/div_write_trigger_volume.gb", "samesuite/apu/div_write_trigger_volume.png",
               COLOR_TOLERANCE_MEDIUM},
            F {"samesuite/apu/div_write_trigger_volume_10.gb", "samesuite/apu/div_write_trigger_volume_10.png",
               COLOR_TOLERANCE_MEDIUM}, );
    }
#else
    SECTION("wip") {
        RUN_TEST_ROMS();
    }
#endif
}

#endif // CGBTESTS_H