on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      c_compiler:
        required: true
        type: string
      cpp_compiler:
        required: true
        type: string
      build_type:
        required: true
        type: string
      run_tests:
        required: false
        type: boolean
        default: false
      upload_artifact:
        required: false
        type: boolean
        default: false
      artifact_name:
        required: false
        type: string
        default: ${{ inputs.os }}-${{ inputs.build_type }}-${{ inputs.c_compiler }}
      artifact_path:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      # Checkout and update submodules recursively.
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Configure project.
      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ inputs.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ inputs.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
          -DBUILD_TESTS=${{ inputs.run_tests }}
          -DENABLE_SERIAL=${{ inputs.run_tests }}
          -DENABLE_AUDIO_PCM=${{ inputs.run_tests }}
          -S ${{ github.workspace }}

      # Build project.
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ inputs.build_type }}

      # Run tests [optional]
      - name: Run Tests
        if: ${{ inputs.run_tests }}
        run: ctest --build-config ${{ inputs.build_type }} --output-on-failure
        working-directory: ${{ github.workspace }}/build

      # Upload artifact [optional]
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifact }}
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}