name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  # Build with the following configurations:
  # 1. DMG, Linux
  # 2. DMG, Windows
  # 3. CGB, Linux
  # 4. CGB, Windows
  build-dmg-docboy-sdl-linux:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: false
      upload_artifact: true
      artifact_name: docboy-dmg-sdl-linux
      artifact_path: build/docboy-dmg-sdl

  build-dmg-docboy-sdl-windows:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
      build_type: Release
      enable_cgb: false
      upload_artifact: true
      artifact_name: docboy-dmg-sdl-windows
      artifact_path: build\Release\docboy-dmg-sdl.exe

  build-cgb-docboy-sdl-linux:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: true
      upload_artifact: true
      artifact_name: docboy-cgb-sdl-linux
      artifact_path: build/docboy-cgb-sdl

  build-cgb-docboy-sdl-windows:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
      build_type: Release
      enable_cgb: true
      upload_artifact: true
      artifact_name: docboy-cgb-sdl-windows
      artifact_path: build\Release\docboy-cgb-sdl.exe

  # Wait for all the builds, then bundle them and create a new release.
  deploy:
    needs: [build-dmg-docboy-sdl-linux, build-dmg-docboy-sdl-windows, build-cgb-docboy-sdl-linux, build-cgb-docboy-sdl-windows]
    runs-on: ubuntu-latest
    steps:
      # Download Linux build.
      - name: Download docboy-dmg-sdl-linux
        uses: actions/download-artifact@v4
        with:
          name: docboy-dmg-sdl-linux
          path: docboy-dmg-sdl-linux

      # Download Windows build.
      - name: Download docboy-dmg-sdl-windows
        uses: actions/download-artifact@v4
        with:
          name: docboy-dmg-sdl-windows
          path: docboy-dmg-sdl-windows

      # Package Linux build.
      - name: Package docboy-cgb-sdl-linux
        run: |
          cd docboy-cgb-sdl-linux
          zip -r ../docboy-cgb-sdl-linux.zip .

      # Package Windows build.
      - name: Package docboy-cgb-sdl-windows
        run: |
          cd docboy-cgb-sdl-windows
          zip -r ../docboy-cgb-sdl-windows.zip .

      - name: Display structure of downloaded files
        run: ls -laR

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ inputs.version }}
          files: |
            docboy-dmg-sdl-windows.zip
            docboy-dmg-sdl-linux.zip
            docboy-cgb-sdl-windows.zip
            docboy-cgb-sdl-linux.zip