name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  # Build with the following configurations:
  # 1. DMG, Linux
  # 2. DMG, Windows
  # 3. CGB, Linux
  # 4. CGB, Windows
  build-dmg-docboy-sdl-linux:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: false
      upload_artifact: true
      artifact_name: docboy-dmg-sdl-linux
      artifact_path: build/docboy-sdl

  build-dmg-docboy-sdl-windows:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
      build_type: Release
      enable_cgb: false
      upload_artifact: true
      artifact_name: docboy-dmg-sdl-windows
      artifact_path: build\Release\docboy-sdl.exe

  build-cgb-docboy-sdl-linux:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: true
      upload_artifact: true
      artifact_name: docboy-cgb-sdl-linux
      artifact_path: build/docboy-sdl

  build-cgb-docboy-sdl-windows:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
      build_type: Release
      enable_cgb: true
      upload_artifact: true
      artifact_name: docboy-cgb-sdl-windows
      artifact_path: build\Release\docboy-sdl.exe

  # Wait for all the builds, then bundle them and create a new release.
  deploy:
    needs: [build-dmg-docboy-sdl-linux, build-dmg-docboy-sdl-windows, build-cgb-docboy-sdl-linux, build-cgb-docboy-sdl-windows]
    runs-on: ubuntu-latest
    steps:
      # Download DMG Linux build.
      - name: Download docboy-dmg-sdl-linux
        uses: actions/download-artifact@v8
        with:
          name: docboy-dmg-sdl-linux
          path: docboy-dmg-sdl-linux

      # Download DMG Windows build.
      - name: Download docboy-dmg-sdl-windows
        uses: actions/download-artifact@v8
        with:
          name: docboy-dmg-sdl-windows
          path: docboy-dmg-sdl-windows.exe

      # Download CGB Linux build.
      - name: Download docboy-dmg-sdl-linux
        uses: actions/download-artifact@v8
        with:
          name: docboy-cgb-sdl-linux
          path: docboy-cgb-sdl-linux

      # Download CGB Windows build.
      - name: Download docboy-dmg-sdl-windows
        uses: actions/download-artifact@v8
        with:
          name: docboy-cgb-sdl-windows
          path: docboy-cgb-sdl-windows.exe

      - name: Display structure of downloaded files
        run: ls -laR

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          files: |
            docboy-dmg-sdl-linux
            docboy-dmg-sdl-windows.exe
            docboy-cgb-sdl-linux
            docboy-cgb-sdl-windows.exe
