name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  # Build for all the platforms.
  build-docboy-sdl-linux:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      upload_artifact: true
      artifact_name: docboy-sdl-linux
      artifact_path: build/docboy-sdl

  build-docboy-sdl-windows:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
      build_type: Release
      upload_artifact: true
      artifact_name: docboy-sdl-windows
      artifact_path: build\Release\docboy-sdl.exe

  # Wait for all the builds, then bundle them and create a new release.
  deploy:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      # Download Linux build.
      - name: Download docboy-sdl-linux
        uses: actions/download-artifact@v4
        with:
          name: docboy-sdl-linux
          path: docboy-sdl-linux

      # Download Windows build.
      - name: Download docboy-sdl-windows
        uses: actions/download-artifact@v4
        with:
          name: docboy-sdl-windows
          path: docboy-sdl-windows

      # Package Linux build.
      - name: Package docboy-sdl-linux
        run: |
          cd docboy-sdl-linux
          zip -r ../docboy-sdl-linux.zip .

      # Package Windows build.
      - name: Package docboy-sdl-windows
        run: |
          cd docboy-sdl-windows
          zip -r ../docboy-sdl-windows.zip .

      - name: Display structure of downloaded files
        run: ls -laR

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ inputs.version }}
          files: |
            docboy-sdl-windows.zip
            docboy-sdl-linux.zip