name: Tests

on: push

jobs:
  # Build for linux and run tests.

  # DMG
  build-linux-gcc-and-test-dmg:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: false
      run_tests: true

  # CGB
  build-linux-gcc-and-test-cgb:
    uses: ./.github/workflows/apply-to-single-platform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release
      enable_cgb: true
      run_tests: true
